ARG PYTHON_VERSION=3.10

FROM python:${PYTHON_VERSION}

ENV POETRY_HOME="/opt/poetry"
ENV PATH="$POETRY_HOME/bin:$PATH"

RUN curl -sSL https://install.python-poetry.org | python -

WORKDIR /usr/src/app

ADD ./src/ /usr/src/app
RUN poetry install